---
abstract: 'FusionInventory unified Agent for UNIX, Linux, Windows and MacOSX'
author:
  - 'FusionInventory Team'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Copy::Recursive: 0
  HTTP::Proxy: 0
  HTTP::Server::Simple: 0
  HTTP::Server::Simple::Authen: 0
  IO::Capture::Stderr: 0
  IO::Socket::SSL: 0
  IPC::Run: 0
  JSON::PP: 0
  LWP::Protocol::https: 0
  Net::SNMP: 0
  Parallel::ForkManager: 0
  Test::Compile: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: '0.93'
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent
no_index:
  directory:
    - inc
    - share
    - t
  file:
    - bin/setup.pm
provides:
  FusionInventory::Agent: 2.3.20
recommends:
  Archive::Extract: 0
  Compress::Zlib: 0
  DateTime: 0
  Digest::SHA: 0
  File::Copy::Recursive: 0
  HTTP::Daemon: 0
  IO::Socket::SSL: '1.14'
  JSON::PP: 0
  LWP::Protocol::https: 0
  Net::CUPS: 0.6
  Net::NBName: 0
  Net::Ping: 0
  Net::SNMP: 0
  Net::Write::Layer2: 0
  Parallel::ForkManager: 0
  Parse::EDID: 0
  Proc::Daemon: 0
  Proc::PID::File: 0
  Thread::Queue: '2.01'
  URI::Escape: 0
requires:
  File::Which: 0
  LWP::UserAgent: '5.8'
  Net::IP: 0
  Text::Template: 0
  UNIVERSAL::require: 0
  XML::TreePP: '0.26'
  perl: 5.8.0
resources:
  IRC: irc://irc.freenode.net/#fusioninventory
  bugtracker: https://github.com/fusioninventory/fusioninventory-agent/issues
  homepage: http://www.fusioninventory.org
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/fusioninventory/fusioninventory-agent/
version: 2.3.20
